apiVersion: v1
kind: Service
metadata:
  name: controller-manager-metrics-service
  namespace: kagent
  labels:
    app.kubernetes.io/name: kagent-hook-controller
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: kagent-hook-controller
    app.kubernetes.io/part-of: kagent-hook-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: kagent-hook-controller
    app.kubernetes.io/instance: controller-manager