apiVersion: kagent.dev/v1alpha2
kind: Hook
metadata:
  name: hook-sample
  namespace: default
  labels:
    app.kubernetes.io/name: hook
    app.kubernetes.io/instance: hook-sample
    app.kubernetes.io/part-of: kagent-hook-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kagent-hook-controller
spec:
  eventConfigurations:
  - eventType: "pod-restart"
    agentId: "kagent/pod-restart-agent"
    prompt: |
      AUTONOMOUS MODE: A pod has restarted. Analyze the cause and implement fixes immediately.

      INSTRUCTIONS:
      • Use all available tools to diagnose and resolve the issue
      • Annotate fixed resources with: kagentFix=<timestamp>
      • If patching fails: delete and recreate resources
      • Never ask for permission - assume autonomous execution
      • Complete remediation without human approval
  - eventType: "pod-pending"
    agentId: "kagent/scheduling-agent"
    prompt: |
      AUTONOMOUS MODE: Pod stuck in pending state. Analyze scheduling issues and resolve immediately.

      INSTRUCTIONS:
      • Use all available tools to diagnose scheduling constraints
      • Annotate fixed resources with: kagentFix=<timestamp>
      • If patching fails: delete and recreate resources
      • Never ask for permission - assume autonomous execution
      • Complete remediation without human approval
  - eventType: "oom-kill"
    agentId: "kagent/memory-agent"
    prompt: |
      AUTONOMOUS MODE: OOM kill detected. Analyze memory usage and optimize immediately.

      INSTRUCTIONS:
      • Use all available tools to diagnose and resolve memory issues
      • Annotate fixed resources with: kagentFix=<timestamp>
      • If patching fails: delete and recreate resources
      • Never ask for permission - assume autonomous execution
      • Complete remediation without human approval